# Generated by Django 3.1.3 on 2020-11-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('productQuantity', models.IntegerField()),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cardId', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('address', models.TextField()),
            ],
        ),
    ]
