# Generated by Django 3.1.3 on 2020-11-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='productId',
            new_name='orderQuantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='productQuantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='unitPrice',
        ),
    ]
