# Generated by Django 3.1.3 on 2020-11-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201129_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orderQuantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total',
        ),
        migrations.AddField(
            model_name='orders',
            name='productsId',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
