# Generated by Django 3.1.3 on 2020-11-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
