# Generated by Django 3.1.3 on 2020-11-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
