# Generated by Django 3.1.3 on 2020-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='author',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
