# Generated by Django 3.1.3 on 2020-11-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_stock_quantity_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock_quantity_base',
        ),
    ]
